apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: moaraudio 
  janus-idp.io/tekton: moaraudio
  backstage.io/kubernetes-id: moaraudio
  backstage.io/kubernetes-namespace: ai-rhdh-app-development 
  app.kubernetes.io/part-of: moaraudio
resources: 
- application-dev.yaml